// Illustrative scenario animations. n: [label,x,y,kind] (kind r=threat, s=control); f: [route(node indexes), colour r|g|b]; l: log lines.
export const scenes = {
  'cloud-solutions': { n: [['On-premises', 70, 150], ['Landing zone', 270, 150, 's'], ['Azure', 490, 60], ['AWS', 490, 150], ['Alibaba Cloud', 490, 240]], f: [[[0, 1, 2], 'b'], [[0, 1, 3], 'b'], [[0, 1, 4], 'b']], l: ['Discovery maps servers and dependencies', 'Landing zone applies policy and identity', 'Wave 1 migrated with minimal downtime', 'Cost review removes idle resources'] },
  'cloud-desktop': { n: [['User device', 70, 150], ['Entra ID + Intune', 270, 150, 's'], ['Virtual desktop', 490, 70], ['Company data', 490, 230], ['Unmanaged PC', 70, 260, 'r']], f: [[[0, 1, 2], 'b'], [[0, 1, 3], 'g'], [[4, 1], 'r']], l: ['Device compliance checked at sign-in', 'Conditional access grants the session', 'Unmanaged device blocked', 'Company data stays inside the tenant'] },
  'managed-it': { n: [['Servers', 70, 60], ['Endpoints', 70, 240], ['Monitoring', 270, 150, 's'], ['Help desk', 490, 70], ['Monthly report', 490, 230]], f: [[[0, 2, 3], 'b'], [[1, 2, 3], 'b'], [[2, 4], 'g']], l: ['Alert: disk space low on file server', 'Ticket created and assigned', 'Patch window completed', 'Report shows what was fixed'] },
  'network-solutions': { n: [['Internet', 70, 150], ['Firewall', 270, 150, 's'], ['Staff VLAN', 490, 60], ['Server VLAN', 490, 150], ['ClearPass NAC', 490, 240], ['Unknown device', 70, 260, 'r']], f: [[[0, 1, 2], 'b'], [[0, 1, 3], 'b'], [[1, 4], 'g'], [[5, 1], 'r']], l: ['Traffic inspected at the perimeter', 'Staff and servers kept in separate VLANs', 'Unknown device denied by NAC', 'Remote user connects over VPN'] },
  'disaster-recovery': { n: [['Production', 70, 150], ['Backup', 270, 150], ['Immutable vault', 490, 60, 's'], ['DR site', 490, 240], ['Ransomware', 70, 40, 'r']], f: [[[4, 0], 'r'], [[0, 1, 2], 'g'], [[2, 3], 'b']], l: ['Ransomware encrypts production files', 'Immutable backup copy is untouched', 'Restore to the DR site begins', 'Services back within the target RTO'] },
  'cyber-security': { n: [['Attacker', 70, 50, 'r'], ['Phishing email', 70, 250, 'r'], ['XDR + firewall', 270, 150, 's'], ['Servers', 490, 60], ['Sensitive data', 490, 150], ['SIEM', 490, 240]], f: [[[0, 2], 'r'], [[1, 2], 'r'], [[2, 3], 'b'], [[2, 4], 'b'], [[2, 5], 'g']], l: ['Brute-force attempt blocked', 'Phishing attachment quarantined', 'EDR isolates the affected host', 'DLP stops a sensitive file upload'] },
  'support-consulting': { n: [['Business goals', 70, 150], ['Analysis', 270, 150, 's'], ['Options', 490, 70], ['Roadmap', 490, 230]], f: [[[0, 1, 2], 'b'], [[0, 1, 3], 'g']], l: ['Goals and constraints gathered', 'Current systems analysed', 'Options compared with cost and risk', 'Roadmap agreed and handed over'] },
  'web-applications': { n: [['Browser', 70, 150], ['API gateway', 270, 150, 's'], ['App server', 490, 70], ['Database', 490, 230], ['Bot traffic', 70, 260, 'r']], f: [[[0, 1, 2], 'b'], [[2, 3], 'g'], [[4, 1], 'r']], l: ['Request authenticated at the gateway', 'Input validated before it reaches the app', 'Bot traffic rate-limited', 'Data saved and backed up'] },
  'mobile-applications': { n: [['Phone app', 70, 150], ['Backend API', 270, 150, 's'], ['Push service', 490, 70], ['Data store', 490, 230]], f: [[[0, 1, 2], 'b'], [[0, 1, 3], 'g']], l: ['App signs in with a secure token', 'Data syncs when online', 'Push notification delivered', 'New release submitted to app stores'] },
  'web-design-development': { n: [['Design', 70, 150], ['Build', 270, 150, 's'], ['Test', 490, 70], ['Live site', 490, 230]], f: [[[0, 1, 2], 'b'], [[2, 3], 'g']], l: ['Wireframes approved', 'Responsive pages built', 'Speed and accessibility tested', 'Site published'] },
  'seo': { n: [['Search query', 70, 150], ['Search engine', 270, 150, 's'], ['Your site', 490, 70], ['Competitor', 490, 230]], f: [[[0, 1, 2], 'g'], [[1, 3], 'b']], l: ['Keywords researched', 'Pages and metadata optimised', 'Site indexed and ranked', 'Visits and leads tracked'] },
  'digital-marketing': { n: [['Campaign', 70, 150], ['Audience', 270, 150, 's'], ['Website', 490, 70], ['Leads', 490, 230]], f: [[[0, 1, 2], 'b'], [[2, 3], 'g']], l: ['Audience defined', 'Ads and content published', 'Visitors reach the website', 'Leads measured and nurtured'] },
  'full-stack-apps': { n: [['Frontend', 70, 150], ['API', 270, 150, 's'], ['Services', 490, 70], ['Database', 490, 230]], f: [[[0, 1, 2], 'b'], [[1, 3], 'g']], l: ['User action sent to the API', 'Business logic runs in services', 'Data stored in the database', 'Automated tests gate each release'] },
  'ecommerce': { n: [['Shopper', 70, 150], ['Storefront', 270, 150, 's'], ['Payment provider', 490, 70], ['Orders', 490, 230], ['Fraud bot', 70, 260, 'r']], f: [[[0, 1, 2], 'b'], [[2, 1, 3], 'g'], [[4, 1], 'r']], l: ['Cart and checkout started', 'Payment handled by the provider', 'Fraud bot blocked', 'Order confirmed and fulfilled'] },
  'hosting-maintenance': { n: [['Visitors', 70, 150], ['CDN + hosting', 270, 150, 's'], ['Backups', 490, 70], ['Monitoring', 490, 230], ['Malicious bot', 70, 260, 'r']], f: [[[0, 1], 'b'], [[1, 2], 'g'], [[1, 3], 'g'], [[4, 1], 'r']], l: ['Pages served from the edge', 'Nightly backup completed', 'Uptime alert acknowledged', 'Updates applied and verified'] },
};
